spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ourmemory
    username: terranking
    password:
    driver-class-name: org.h2.Driver #h2 database ??
  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
server:
  servlet:
    encoding:
      force-response: true
jwt:
  secret:
    b25seXBsc3NvbnRlcnJhbmtpbmdiYWNrZW5kbmV3YmllbXluYW1laXNwYXJranVuZ2d5dW5wbGVhc2VlbmNvZGVvdmVyMjU2Yml0cw==
