spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ourmemory
    username: terranking
    password:
    driver-class-name: org.h2.Driver #h2 database ??
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
server:
  servlet:
    encoding:
      force-response: true
